### ISSUE TITLE
Add support for i18n

### ISSUE THREAD

**Issue by joostdecock** [freesewing/tile#4]
We should make our tiler support multiple languages, in preparation of our multi-language website.

Specifically, we need a command line option to set the language that defaults to `en` and have the strings that it outputs translated.

**Comment by woutervdub** [comment]
I'm assuming you would like to use .yml files to store the strings in. Can we just use a simple version?
cover_page: "cover page"
page: "page"

Without adding sections to the file. I'd like to keep this as simple as possible as to not have to add too much to the current tiler.

**Comment by joostdecock** [comment]
You can do whatever you like or is easiest. It's only a couple of strings, you can put them in the C code for all I care. We'll just patch it when we add another language

**Comment by woutervdub** [comment]
Completed.

Language files: "tile.*language code*.yml"
Should be in the same directory as tile

Format of the language file follows that of the pattern language files:
"English default prompt": "Nederlandse standaard opmerking"

Source code follows the standard set in the pattern PHP files, modified to the C environment.

**Comment by joostdecock** [comment]
Thank you @woutervdub for this great contribution. I'm going to tend to this PR when I get through some of the site work.

**Comment by woutervdub** [comment]
Sorry about the conflict. I forgot to `pull upstream` and missed your logo update. Trying to paste that back in resulted in a bunch of whitespace being changed. The code is identical.
